server:
  port: 8080
spring:
  application:
    name: auth
  cloud:
    nacos:
      server-addr: 192.168.91.128:8848
      username: nacos
      password: nacos
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        file-extension: yaml
        namespace: dev
        group: DEFAULT_GROUP
        refresh-enabled: true
        shared-configs:
          - data-id: common.yaml
            refresh: true
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: dev
        group: DEFAULT_GROUP
