# todo搬到nacos上
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id                    # 雪花算法（后面补 IdWorker）
      logic-delete-field: deleted           # 全局逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl   # 生产环境关闭 SQL 日志
    # 开发环境可以被 profile 覆盖
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.aw.**.domain

# todo搬到nacos上
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 2000

# todo搬到nacos上
redisson:
  # 单机模式（最常用）
  address: redis://127.0.0.1:6379
  database: 0
  password: yourpassword
  # 集群、主从、哨兵模式也支持，直接改配置

# todo搬到nacos上
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: mall
  domain: https://img.yourdomain.com   # 可选：用 CDN 域名